### ISSUE TITLE
Out temperature only if AC is working

### ISSUE THREAD

**Issue by efipso** [codyc1515/homebridge-panasonic-air-conditioner#10]
Since last update (1.1.0) I can only get the outside temperature if the AC is working, and I get the last registered if AC is off.
Before that update, I always get the outside temperature, with AC on and off.

**Comment by codyc1515** [comment]
See issue #9.

Closing.

**Comment by efipso** [comment]
Is not because lack of general connection, it happens before issue #9 and just after 1.1.0 update
