### ISSUE TITLE
Failed connection when app version changes

### ISSUE THREAD

**Issue by efipso** [codyc1515/homebridge-panasonic-air-conditioner#11]
Hi,

This is related to issue #9 and pull request #8 

When app updates with new version, plugin will fail again until you change manually to the correct version. 
This "validation" is not with exact version, but with minimum version. So if you change version with a higher value (for example 99.0) will solve this problem (until app reaches 99.0.1 or higher...)

**Comment by codyc1515** [comment]
Hi there

This was fixed with issue #9. I personally don't think it is good idea if we put it at 99 in case the API changes and it causes some majorly unexpected behaviour. I have changed the package to make it easy to change the version however.

:)
