### ISSUE TITLE
Request for other Air Con Controllers?

### ISSUE THREAD

**Issue by mitch7391** [codyc1515/homebridge-panasonic-air-conditioner#12]
This probably isn’t the best place to post this, but wondering if you would be able to work on the E-zone Controller by Ambience/Advantage Air (uses E-zone app)? I would love to get a Homebridge plug-in for this but don’t have the know how. 

Another person who contacted me has created individual switches for each function of the AC through HTTP commands.

![DC1E0E9B-FCB6-402A-8CB5-0E5F0AA52026](https://user-images.githubusercontent.com/40288237/63508507-b21c7680-c50c-11e9-8ae7-a71de1e7bc06.jpeg)
![DEDA5815-4837-4E34-AC29-B26560BC425B](https://user-images.githubusercontent.com/40288237/63508509-b2b50d00-c50c-11e9-828a-dd3ab06663b1.png)

**Comment by kongjudas** [comment]
I would love to see support for the Panasonic Flagship, model CS-HZ25UKE and CS-HZ35UKE. These are both models with internal wifi.

**Comment by codyc1515** [comment]
@mitch7391 can you please email me at codyc1515@icloud.com with more information? Ideally if you can send me the plug-in files as well, then this will be fairly straight forward.

@kongjudas can you please raise a separate issue for this and include your HomeBridge log (along with any errors, etc., you may be receiving)? Also is this AC using the Comfort Cloud app or some other app?

**Comment by mitch7391** [comment]
Hey @codyc1515, I have had small successes with this since I first posted. I have since found a forum by the company that shares the API or parts of it, which has given me the ‘get’ command. This presents a Jason file that an awesome person on Reddit has helped me learn how to parse it using ‘jq’; I was then able to use that with a curl command to see my temperatures on my RPi. Next was finding an existing plugin I could use to display this as a Temp Sensor to start small, I was able to get it to work with Homebridge-HTTP-Accessory, but it lacks documentation and am still trying to get the developer to help me. I also got it working as Temp Sensors with Homebridge-Cmd4, but I do not understand that plugin at all or how to make the bash files (someone on Reddit was kind enough to make one for me that works). At the end of the day Id love you get this to the stage that everyone could benefit from that has this air con. If you are still interested I can send you all the work I have collected so far and see if you think it is possible?

**Comment by codyc1515** [comment]
Please email me on the email above & I will take a look when I have a spare moment (which is not often lately).

**Comment by mitch7391** [comment]
I did send an email when I made my last comment (maybe went to junk mail?) I have made further progress in cmd4 with this and currently have it in HomeKit, but not yet functional (fine tuning a bash script with little experience and lots of errors). I can email what else I have done and completely understand if you don’t have much time on your hands.
