### ISSUE TITLE
Update to Panasonic App

### ISSUE THREAD

**Issue by miguelsasso** [codyc1515/homebridge-panasonic-air-conditioner#16]
Hi

Device stopped responding as of this morning. Some error related to a new app being released, can’t login. Presume this is a change related to the Panasonic cloud server?

Thanks, Miguel

**Comment by codyc1515** [comment]
Fixed in d65e1c10d2e7b5fc50ea6ea5933437d6fa28fa7d

**Comment by miguelsasso** [comment]
Thanks!
