### ISSUE TITLE
TypeError: this._login is not a function

### ISSUE THREAD

**Issue by miguelsasso** [codyc1515/homebridge-panasonic-air-conditioner#18]
The plugin works initially, then within say 24 hours of the Homebridge service starting, I get an error message and Homebridge shuts down...  I'm running HOOBS if that makes any difference.

[Homebridge] [3/7/2020, 10:37:48 AM] [Air Con] GET CurrentTemperature
[Homebridge] [3/7/2020, 10:37:48 AM] [Air Con] GET ThresholdTemperature
[Homebridge] [3/7/2020, 10:47:57 AM] [Air Con] GET Active
[Homebridge] [3/7/2020, 10:47:57 AM] [Air Con] GET ThresholdTemperature
[Homebridge] [3/7/2020, 10:47:57 AM] [Air Con] GET CurrentTemperature
[Homebridge] [3/7/2020, 1:04:27 PM] TypeError: this._login is not a function
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-panasonic-air-conditioner/index.js:34:31)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[Homebridge] [3/7/2020, 1:04:27 PM] Got SIGTERM, shutting down service...

**Comment by miguelsasso** [comment]
See item #21 for workaround.

**Comment by codyc1515** [comment]
I think I found the issue. The `.bind(this)` part was missing from the login token refresh call. This worked on my end but maybe there is some reason it doesn't work on yours so I have added this now.
