### ISSUE TITLE
plugin kills Hoobs service

### ISSUE THREAD

**Issue by ursusHU** [codyc1515/homebridge-panasonic-air-conditioner#21]
After installing the plugin on Hoobs, the Hoobs service is stopped exactly 3 hours after starting. 

[Homebridge] [3/17/2020, 11:09:02 PM] [AC 2.5] Initializing PanasonicAirConditioner accessory...
[Homebridge] [3/17/2020, 11:09:06 PM] [AC 2.5] Logged into Panasonic account
[...]
[Homebridge] [3/18/2020, 2:09:02 AM] TypeError: this._login is not a function
at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/homebridge-panasonic-air-conditioner/index.js:34:31)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
[Homebridge] [3/18/2020, 2:09:02 AM] Got SIGTERM, shutting down service...

it is reproducible.
Could you take a look?

**Comment by miguelsasso** [comment]
I posted the same issue a couple of weeks back (issue #18).

The index.js script runs the following every 3 hours (10800000 milliseconds):

// Refresh the login token every 3 hours
	setInterval(function() {this._login();}, 10800000);

Which somehow causes the script to crash.  I don't know how to code in node.js so I wouldn't know how to go about fixing it.

**Comment by miguelsasso** [comment]
That semicolon after this.login() doesn't look right...

**Comment by EvertJob** [comment]
Just remove the line (or make it a comment). Works fine for me

**Comment by miguelsasso** [comment]
Any idea where I can find the index.js?  I'm running HOOBS on a Pi

**Comment by EvertJob** [comment]
You can check this location:
`/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner`

Than restart the service, working fine for over a day right over here without any issue.

**Comment by miguelsasso** [comment]
It seems HOOBS stores the plugins in a different location.  I found them here:

/home/hoobs/.hoobs/node_modules/homebridge-panasonic-air-conditioner

Just commented out that line.  Hopefully it works.  Thanks

**Comment by EvertJob** [comment]
@miguelsasso does it work?

**Comment by ursusHU** [comment]
> 
> 
> @miguelsasso does it work?

Hi! Thanks for the solution, it works since 2 days for me. :)

**Comment by ursusHU** [comment]
My colleague checked the script. A small modification seems to solve the problem. I make a PR.

**Comment by codyc1515** [comment]
Can you please try with the latest update? https://github.com/codyc1515/homebridge-panasonic-air-conditioner/commit/5c4262a642bd0d690eada667603148fee242b699

Note: that this update has a fairly major change. The plugin used to call the server every time you open the Home app (which delays all plugins responses) and will now poll the server every 10 minutes or so. If you are using just the Home app (i.e. not the Comfort Cloud app or the remote) then your information will always be current and this will not be an issue, otherwise it will refresh every ten minutes.

**Comment by ursusHU** [comment]
It is up and running since 12 hours, so the previously reported problem doesn’t exist anymore. Thank you very much for your efforts!

**Comment by codyc1515** [comment]
Glad I could help :)

**Comment by miguelsasso** [comment]
Noted the latest version is configured to poll the server every "10 minutes or so".

I have multiple users in my household so 10 minutes may not be frequent enough.  Could you perhaps provide a user configured parameter to define polling frequency?

**Comment by codyc1515** [comment]
That’s only necessary if you’re using the remote or the Panasonic app. If they’re all using the Home app it should be updated live. Can you please confirm?

**Comment by miguelsasso** [comment]
Some members of my household still use the remote control.  Also, the current temperature is required to be fetched from the Panasonic servers. 

Is there any reason why Panasonic wouldn't allow us to poll their server say, every minute?
