### ISSUE TITLE
midea AC

### ISSUE THREAD

**Issue by hillaliy** [codyc1515/homebridge-panasonic-air-conditioner#23]
Please can you write plugin for midea AC
I found on the net Plugin for midea AC to Home-assistant (python) and Ruby plugin.
Maybe it can help to write the node.js code.

[midea-air-condition-master.zip](https://github.com/codyc1515/homebridge-panasonic-air-conditioner/files/4493463/midea-air-condition-master.zip)
[midea-ac-py-master.zip](https://github.com/codyc1515/homebridge-panasonic-air-conditioner/files/4493465/midea-ac-py-master.zip)

**Comment by codyc1515** [comment]
Hi there, it looks like Home Assistant (HA) supports Midea. HA can expose accessories back to HomeKit.

https://github.com/houselabs/home-assistant-mideaccm
