### ISSUE TITLE
HTTP Response 500

### ISSUE THREAD

**Issue by EvertJob** [codyc1515/homebridge-panasonic-air-conditioner#26]
Currently I'm getting the following errors starting this morning. I've already reset and re-setup the TACG1 and that is working fine. I can control the AC from the original Panasonic app.

`Could not send SET command | HTTP response 500 | Error # 5005 : Adapter Communication error`

Edit: Just to give some more information.

I've been working on a whole new server setup te replace my Raspberry Pi. The software is no longer combined into one big mess but separated with Docker.

I was running the HomeBridge on a separated Pi (due to performance issues) with only one Tasmota device and the Panasonic AC.

Because the new server has more speed I've decided to move the AC to the new server. Everything was working fine but after a couple of hours the link LED start flashing on the TACG1 and won't work anymore.

After some work the adapter started to work as normal, I can login on the Panasonic app and turn on and off the AC. But this plugin keeps failing for no reason.

Then I just restart my old Pi (with working configuration) and there the same issues start showing up so I can trace back the issue to two possibilities 

1: My TAGC1 adapter is broken 
2: Panasonic made some adjustments in the background that prevent using you're own script.

I guess it's two but I hope for one...

**Comment by codyc1515** [comment]
I am having no issues with my Panasonic Wi-Fi adapter.

Just did a quick test where I disrupted the wifi access of the adapter on a hunch and it gave me this exact error. So I'm going to say you may need to check your wifi connectivity where the heat pump is.

**Comment by EvertJob** [comment]
No, there is no issue with my WiFi.

The Panasonic app can always be used and right now I'm testing a plugin voor Home Assistant, both works perfectly.

Only thin I can imagine is that both Panasonic and HA are working in he cloud instead of direct communication. Don't know.

Already contacted Panasonic and still got no answer.

**Comment by codyc1515** [comment]
The error comes from Panasonic's API. I have also never seen it before as I have good connectivity. The only way I can get it to show is if I block the adapter from Wi-Fi access - which causes the issue to happen every time with that exact message. I cannot think of anything else.

Please also bear in mind if you're contacting Panasonic that this is not an official plug-in. They offer very little in the way of support.

**Comment by EvertJob** [comment]
I understand but if the TACG1 is broken than they need to replace it for one that is working correctly. The fact that I could not reconfigure the TACG1 for a couple of hours isn't normal.

**Comment by codyc1515** [comment]
No, that doesn’t sound normal. Do you mind if I asked where you purchased it?

**Comment by EvertJob** [comment]
I’ve bought it at the same person who installed it. Because he didn’t know about the WiFi module I would like to have a answer from Panasonic so I can claim my warranty.

**Comment by EvertJob** [comment]
Ok,

Contacted Panasonic previous weekend and it needs to be said: They understand the issue and need to find out if the issue is related to the TAGCZ1 or to my WiFi network. He is asking a collogue and will send me the results next week.
