### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by peregrines2** [codyc1515/homebridge-panasonic-air-conditioner#3]
<img width="628" alt="Bildschirmfoto 16" src="https://user-images.githubusercontent.com/9152610/58015107-b050aa80-7afa-11e9-86da-ae04f26dc33e.png">

**Comment by codyc1515** [comment]
This is because the _request_ module is not installed. If you run the command `npm install -g request` you should be fine. I will change the package to require this to be installed in the future.

**Comment by peregrines2** [comment]
Thank You very much my friend!
And please excuse me beeing such a noob!
Your package is very much apriciated!!

Best regards,
Felix

**Comment by codyc1515** [comment]
Fixed by pull #4
