### ISSUE TITLE
Feature request - Dry mode

### ISSUE THREAD

**Issue by ursusHU** [codyc1515/homebridge-panasonic-air-conditioner#30]
Would it be possible to add this feature too, or this is a limitation of Homekit?

**Comment by codyc1515** [comment]
Maybe. It would have to be a Dehumidifier service.

**Comment by codyc1515** [comment]
I tried to do this but found it quite difficult. I would welcome any support to get this added.

**Comment by codyc1515** [comment]
Added in 544daca05ae4adf122c32ebba37030b2b234c0fb
