### ISSUE TITLE
Could not load accessory ... missing the required 'name' property

### ISSUE THREAD

**Issue by jsnoble7** [codyc1515/homebridge-panasonic-air-conditioner#31]
Have just loaded up Homebridge and installed the plugin... but I'm seeing this error every time I restart Homebridge (and my Panasonic air con isn't displaying in Homekit):

`Could not load accessory PanasonicAirConditioner at position 1 as it is missing the required 'name' property!`

I've tried installing the plugin both via the UI and also directly via npm (and both installations go fine with no errors).

**Comment by jsnoble7** [comment]
Through trial and error, I resolved this by adding `"name": "PanasonicAirConditioner",` into Homebridge's config file. Not sure why it isn't getting added when I installed the plugin?

So the config file now reads:
```
"accessories": [
        {
            "name": "PanasonicAirConditioner",
            "email": "**@**.com",
            "password": "****",
            "debug": true,
            "accessory": "PanasonicAirConditioner"
        }
```

**Comment by codyc1515** [comment]
This is probably because an assumption is made that most users are using the config-ui-x plugin too. It has support for adding the config automatically. I will add a check for this, however, to prevent the issue.

**Comment by codyc1515** [comment]
Improved error handling added in https://github.com/codyc1515/homebridge-panasonic-air-conditioner/commit/744a04a602779772bf269bd8ec221fccfe42d43c
