### ISSUE TITLE
DeviceNumber error with Multiple Units

### ISSUE THREAD

**Issue by HomekitDave** [codyc1515/homebridge-panasonic-air-conditioner#33]
Hi there,

When attempting to add an additional device using "devicenumber" I get the below result and neither devices work. 

### Config:
      {
            "name": "Air-Conditioner",
            "email": "mail@example.com",
            "password": "******",
            "devicenumber": 1,
            "accessory": "PanasonicAirConditioner"
        },
        {
            "name": "Air-Conditioner 2",
            "email": "mail@example.com",
            "password": "******",
            "devicenumber": 2,
            "accessory": "PanasonicAirConditioner"
        }

### Log:
```
Could not find device by number. Check your device number and try again. TypeError: Cannot read property 'deviceIdList' of undefined
    at PanasonicAC.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:159:60)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) Error # undefined undefined
```

**Comment by codyc1515** [comment]
Sorry I don't have two devices to test with. Would you please be able to email me (codyc1515@icloud.com) with a login that has two devices? I will be able to test it this way.

**Comment by arkadicolson** [comment]
My homebridge config looks like this for 2 units:

{
"name": "Keuken",
"email": "****",
"password": "****",
"accessory": "PanasonicAirConditioner",
"devicenumber": "1"
},
{
"name": "Hal boven",
"email": "****",
"password": "****",
"accessory": "PanasonicAirConditioner",
"devicenumber": "2",
"debug": true
}

The homebridge log:

[9/1/2020, 10:21:01 AM] [Hal boven] Could not find any devices. Error # undefined undefined
HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
[9/1/2020, 10:21:02 AM] [Keuken] Login complete
HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.

Below you can find the raw output of 3 units.

root@homebridge:/opt/python-panasonic-comfort-cloud# ./pcomfortcloud.py -r 1 **** **** list
--- token found
--- _get_groups()
--- raw beginning ---
{
   "groupCount":1,
   "groupList":[
      {
         "groupId":92502,
         "groupName":"Arroyo",
         "deviceIdList":[
            {
               "deviceGuid":"CS-TZ50WKEW+4758703378",
               "deviceType":"3",
               "deviceName":"Keuken",
               "permission":3,
               "deviceModuleNumber":"CS-TZ50WKEW",
               "deviceHashGuid":"55f56af03acd4a5e845ead611620a7c405ae02820560706770089b092c35bfd8",
               "summerHouse":0,
               "iAutoX":false,
               "nanoe":false,
               "autoMode":true,
               "heatMode":true,
               "fanMode":false,
               "dryMode":true,
               "coolMode":true,
               "ecoNavi":false,
               "powerfulMode":true,
               "quietMode":true,
               "airSwingLR":true,
               "ecoFunction":0,
               "temperatureUnit":0,
               "modeAvlList":{
                  "autoMode":1,
                  "fanMode":1
               },
               "parameters":{
                  "operate":0,
                  "operationMode":3,
                  "temperatureSet":21.5,
                  "fanSpeed":1,
                  "fanAutoMode":3,
                  "airSwingLR":2,
                  "airSwingUD":0,
                  "ecoMode":0,
                  "ecoNavi":0,
                  "nanoe":0,
                  "iAuto":0,
                  "actualNanoe":0,
                  "airDirection":1,
                  "ecoFunctionData":0
               }
            },
            {
               "deviceGuid":"CS-TZ50WKEW+4758703394",
               "deviceType":"3",
               "deviceName":"Hal boven",
               "permission":3,
               "deviceModuleNumber":"CS-TZ50WKEW",
               "deviceHashGuid":"8f22212167330f5cb19c9ff7e9ffa30a493803d005df5d038c1b1c4bcdb17e49",
               "summerHouse":0,
               "iAutoX":false,
               "nanoe":false,
               "autoMode":true,
               "heatMode":true,
               "fanMode":false,
               "dryMode":true,
               "coolMode":true,
               "ecoNavi":false,
               "powerfulMode":true,
               "quietMode":true,
               "airSwingLR":true,
               "ecoFunction":0,
               "temperatureUnit":0,
               "modeAvlList":{
                  "autoMode":1,
                  "fanMode":1
               },
               "parameters":{
                  "operate":0,
                  "operationMode":2,
                  "temperatureSet":21.0,
                  "fanSpeed":0,
                  "fanAutoMode":3,
                  "airSwingLR":2,
                  "airSwingUD":0,
                  "ecoMode":0,
                  "ecoNavi":0,
                  "nanoe":0,
                  "iAuto":0,
                  "actualNanoe":0,
                  "airDirection":1,
                  "ecoFunctionData":0
               }
            }
         ]
      }
   ]
}
--- raw ending ---

list of devices and its device id (1-x)
device #1
id : 55f56af03acd4a5e845ead611620a7c405ae02820560706770089b092c35bfd8
name : Keuken
group : Arroyo
model : CS-TZ50WKEW

device #2
id : 8f22212167330f5cb19c9ff7e9ffa30a493803d005df5d038c1b1c4bcdb17e49
name : Hal boven
group : Arroyo
model : CS-TZ50WKEW

After a restart I now got this error:

[9/1/2020, 10:49:14 AM] [Hal boven] Login complete
[9/1/2020, 10:49:14 AM] [Hal boven] Could not find device by number. Check your device number and try again. TypeError: Cannot read property 'deviceIdList' of undefined
at PanasonicAC.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/index.js:159:60)
at Request.self.callback (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:185:22)
at Request.emit (events.js:315:20)
at Request.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1154:10)
at Request.emit (events.js:315:20)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-panasonic-air-conditioner/node_modules/request/request.js:1076:12)
at Object.onceWrapper (events.js:421:28)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (_stream_readable.js:1220:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21) Error # undefined undefined
HAP Warning: Characteristic 00000077-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BC-0000-1000-8000-0026BB765291. Adding anyway.
[9/1/2020, 10:49:14 AM] [Hal boven] Refresh start
[9/1/2020, 10:49:15 AM] [Hal boven] Refresh failed. Authorization error. Did you enter the correct username and password? Please check the details & restart Homebridge. null

If you need more info, just let me know!

**Comment by arkadicolson** [comment]
They update the json output...

You can see the changes here from this project. Perhaps is also helps you to convert it to a platform or make it possible to use more then one unit?

https://github.com/lostfields/python-panasonic-comfort-cloud/commit/a1815fb40a82a9987ed98839ac3cab264817b090#diff-92f36127ed2dbf7eee834fe3064e7987

**Comment by arkadicolson** [comment]
@codyc1515 Do you have enough information to debug the multiple devices issue? It would be nice to have all 3 units in my homekit ;-)

**Comment by passatgt** [comment]
The fix is pretty simple, however i was only got it to work if i used separate accounts for each accessory, because it will request a new token for every accessory and it will overwrite the previous one. 

This is the line that needs to be changed:

`this.device = body['groupList'][this.groupNumber-1]['deviceIdList'][this.deviceNumber-1]['deviceGuid'];`

(so it will select the proper group first)

**Comment by arkadicolson** [comment]
Great to have this already working and thank you for that! But maybe it's an idea to use a .token file somewhere and use the same for all units so there a no need for separate accounts. My nodejs coding is really bad otherwise I would give it a try myself...

**Comment by passatgt** [comment]
Yes, i was just playing around with that. Ideally it should be a platform, so it supports multiple accessories, but thats above my homebridge knowledge at the moment. But creating a single token and store it somehow as a global variable should be a good enough workaround.

**Comment by codyc1515** [comment]
It's above my Homebridge knowledge also, otherwise it will be the best way to support multiple devices. Are you still having issues with multiple devices?

**Comment by arkadicolson** [comment]
I created different accounts for each unit which is not a great solution but for now it works. Is there a place where feature requests are collected? Convert it to a platform module should be on that list.

**Comment by Bedzaa-zz** [comment]
Hi guys, I am absolutely untouched by programming but somehow I could manage the workaround if I have some guide how to do it. I have installed 3 deviced at home and I would wish to make it somehow running. Could You be so kind and help me with step-by-step guide? That will be very much appreciated. Thank You so much! petr.benda@centrum.cz

**Comment by rupertbg** [comment]
Could be related to https://github.com/codyc1515/homebridge-panasonic-air-conditioner/pull/45 since the issue with API version 1.9.0 was that they removed "DeviceIdList" and called it "DeviceList" instead

**Comment by codyc1515** [comment]
Hi all. The API version issue should be resolved now. Let me know how you get on.

**Comment by Bedzaa-zz** [comment]
> Hi all. The API version issue should be resolved now. Let me know how you get on.

Hi Codyc, first of all thank You for Your support!

I`ve received a notification to my e-mail about this fix so I went immediately to my cockpit room and made following adjustments and checks:
1) three AC devices listed in official Comfort Cloud app and account 1 used for mobile access : OK
2) three AC devices listed in official Comfort Cloud app and account 2 used for homekit and this plugin : OK
3) Homebridge settings in config.json:
{
            "name": "Living Room AC",
            "email": "mymail@centrum.cz",
            "password": "xxx",
            "devicenumber": 1,
            "accessory": "PanasonicAirConditioner"
        },
        {
            "name": "Šimon`s Room AC",
            "email": "mymail@centrum.cz",
            "password": "xxx",
            "devicenumber": 2,
            "accessory": "PanasonicAirConditioner"
        },

{
            "name": "Klára`s Room AC",
            "email": "mymail@centrum.cz",
            "password": "xxx",
            "devicenumber": 3,
            "accessory": "PanasonicAirConditioner"
        },
4) homebridge restart : OK
5) status in homekit (three new multiaccessories, each has three items:
- temperature control
- fan control
- something linked to humidity
6) result:
- accessory nr.1 works well and fully
- other accessories do not response, updating and no results is comming back (temperature 0.0, switching on/off does not work. I have taken couple of screenshots should You need some.

I am ready to share this experience in order to You to investigate more and fix the functionality.

Thank You in advance for Your feedback
Cheers
Bedza

**Comment by Bedzaa-zz** [comment]
> Hi all. The API version issue should be resolved now. Let me know how you get on.

- one thing I see strange: in the setting window of the plugin I see only one accessory. For three devices I had to write the code myself directly into the config.json
- when I have updated the debug option and hit SAVE, then the debug line appeared in device 1 only

And some info from the log:
[02/01/2021, 12:08:43] [Living Room AC] Could not find any devices. Error # undefined undefined
[02/01/2021, 12:08:43] [Šimon`s Room AC] Could not find any devices. Error # undefined undefined
[02/01/2021, 12:08:44] [Klára`s Room AC] Login complete
[02/01/2021, 12:08:44] [Klára`s Room AC] Refresh start
[02/01/2021, 12:08:45] [Klára`s Room AC] {
  deviceGuid: 'C7xxxxxxxx',
  timestamp: 1609585587000,
  summerHouse: 0,
  iAutoX: false,
  nanoe: false,
  autoMode: true,
  heatMode: true,
  fanMode: false,
  dryMode: true,
  coolMode: true,
  ecoNavi: false,
  powerfulMode: true,
  permission: 2,
  quietMode: true,
  airSwingLR: true,
  ecoFunction: 0,
  temperatureUnit: 0,
  modeAvlList: { autoMode: 1, fanMode: 1 },
  parameters: {
    devGuid: 'C785081968',
    eventTime: null,
    online: true,
    operate: 0,
    operationMode: 0,
    temperatureSet: 25,
    fanSpeed: 0,
    fanAutoMode: 1,
    airSwingLR: 2,
    airSwingUD: 0,
    airDirection: 0,
    ecoMode: 0,
    ecoNavi: 1,
    nanoe: 0,
    iAuto: 0,
    defrosting: -255,
    errorCode: null,
    errorCodeStr: null,
    insideTemperature: 126,
    outTemperature: 126,
    devRacCommunicateStatus: -255,
    errorStatus: -255,
    errorStatusFlg: false,
    httpErrorCode: -255,
    actualNanoe: 0,
    airQuality: 0,
    ecoFunctionData: 0,
    updateTime: 1609585587000
  },
  autoTempMax: -1,
  dryTempMax: -1,
  heatTempMax: -1,
  coolTempMax: -1,
  autoTempMin: -1,
  dryTempMin: -1,
  heatTempMin: -1,
  coolTempMin: -1,
  fanSpeedMode: -1,
  fanDirectionMode: -1
}
[02/01/2021, 12:08:45] [Klára`s Room AC] Temperature state is not available 126 126
[02/01/2021, 12:08:45] [Klára`s Room AC] Refresh complete
[02/01/2021, 12:13:13] [Living Room AC] SET TargetHeatingCoolingState 0 start
[02/01/2021, 12:13:14] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires
[02/01/2021, 12:13:39] [Living Room AC] SET FanActive 1 start
[02/01/2021, 12:13:39] [Living Room AC] SET RotationSpeed 2 start
[02/01/2021, 12:13:39] [Living Room AC] SET RotationSpeed 4 start
[02/01/2021, 12:13:39] [Living Room AC] SET RotationSpeed 2 start
[02/01/2021, 12:13:39] [Living Room AC] SET RotationSpeed 4 start
[02/01/2021, 12:13:39] [Living Room AC] SET TargetFanState 1 start
[02/01/2021, 12:13:40] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires
[02/01/2021, 12:13:40] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires
[02/01/2021, 12:13:41] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires
[02/01/2021, 12:13:41] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires
[02/01/2021, 12:13:41] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires
[02/01/2021, 12:13:41] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires
[02/01/2021, 12:13:42] [Living Room AC] SET TargetHeatingCoolingState 0 start
[02/01/2021, 12:13:43] [Living Room AC] SET failed. HTTP response 401 Error # 4100 Token expires

**Comment by codyc1515** [comment]
Can you please share some screenshots? Also corresponding comfort cloud app screenshots? It may well be your heat pump does not support these functions. I hope to be able to add some code for this in the future.

**Comment by Bedzaa-zz** [comment]
> Can you please share some screenshots? Also corresponding comfort cloud app screenshots? It may well be your heat pump does not support these functions. I hope to be able to add some code for this in the future.

![1C1E4011-0DC8-4663-A3D8-2ED386B30ADE](https://user-images.githubusercontent.com/45871405/103456661-9cba7d80-4cf8-11eb-9d35-1ba7d7bafd93.jpeg)
![B295F2E4-2E59-41DF-984A-EB7D182EAD91](https://user-images.githubusercontent.com/45871405/103456663-9e844100-4cf8-11eb-817a-04f6468bb000.jpeg)
![474A6BF9-EE49-46F2-871E-565A4A024FAB](https://user-images.githubusercontent.com/45871405/103456664-9f1cd780-4cf8-11eb-8446-d80ac041db20.jpeg)
![CC65ADBC-6F7D-4663-8598-0C59DCE2FEE4](https://user-images.githubusercontent.com/45871405/103456665-9fb56e00-4cf8-11eb-9b3b-b5adc4ea8ced.jpeg)
![B1A1E471-BB71-4BD9-940F-D4BFB23C2476](https://user-images.githubusercontent.com/45871405/103456666-9fb56e00-4cf8-11eb-929a-84da7add4ea9.jpeg)
![648AB7BF-05FD-4735-9B53-2EB9412E36A0](https://user-images.githubusercontent.com/45871405/103456668-a04e0480-4cf8-11eb-81b9-c2e44463a216.jpeg)

**Comment by Bedzaa-zz** [comment]
> Can you please share some screenshots? Also corresponding comfort cloud app screenshots? It may well be your heat pump does not support these functions. I hope to be able to add some code for this in the future.

All three AC devices are the same age, with the same Panasonic Wi-Fi module. 
Now, after the debug:true the other started to work, but the very first one stopped :-) it behaves strange

**Comment by rupertbg** [comment]
Hey @Bedzaa - by the looks of it you need to make one Panasonic account per AC device. An example of this is at the bottom of the readme.

You then invite each Panasonic account to a single (one) AC device. In your `config.json` you then configure each device individually with each it's own Panasonic account credentials. Hope this helps.

**Comment by rupertbg** [comment]
In your case it would look like:
```
  {
        "name": "Air-Conditioner",
        "email": "mail1@example.com",
        "password": "******",
        "devicenumber": 1,
        "accessory": "PanasonicAirConditioner"
    },
    {
        "name": "Air-Conditioner 2",
        "email": "mail2@example.com",
        "password": "******",
        "devicenumber": 1,
        "accessory": "PanasonicAirConditioner"
    }
```

**Comment by Bedzaa-zz** [comment]
> Hey @Bedzaa - by the looks of it you need to make one Panasonic account per AC device. An example of this is at the bottom of the readme.
> 
> You then invite each Panasonic account to a single (one) AC device. In your `config.json` you then configure each device individually with each it's own Panasonic account credentials. Hope this helps.

Thank You for Your interest into my case. I have done it and it simply works!!! A bit crazy workaround, but solved. All three units in my house are Homekit compatible now! Thank You!

**Comment by JurgenLB** [comment]
I use 4 separated E-mail for controlling the AC;
1 is on my phone the other 3 are for Hombridge.
This is 1 E-mail for 1 indoor unit. I have this setup for +1year now, sometimes there are issues with update but for the rest it works great. thanks for the work.

My config looks like this;
    "accessories": [
         {
              "accessory": "PanasonicAirConditioner",
              "name": "Airco 1",
              "email": "@1",
              "password": "1"
         },
         {
              "accessory": "PanasonicAirConditioner",
              "name": "Airco 2",
              "email": "@2",
              "password": "2"
         },
         {
              "accessory": "PanasonicAirConditioner",
              "name": "Airco 3",
              "email": "@3",
              "password": "3"
         }
    ],

**Comment by rupertbg** [comment]
Yeah I use this same approach for two units. One thing worth mentioning is if you are using gmail then you can use the +format to make more email addresses off your existing one, without having to sign up for another email account. This approach is mentioned here: https://gmail.googleblog.com/2008/03/2-hidden-ways-to-get-more-from-your.html

**Comment by codyc1515** [comment]
Hi all. Sorry for the delay in replying. Yes - you would need to have one account per each heat pump. Unless someone here knows how to convert this plug-in to a platform, we are struck with this. We could do a workaround like store the token somewhere in the file system but this is not ideal.

**Comment by xahmol** [comment]
EDIT: SOLVED.
Just saw that above here somebody posted the JSON without the "devicenumber" lines. So tried that, and voila, it works!
So I have it working now with the JSON entry as JurgenLB above (so removing my "devicenumber" lines).
My suggestion would be to change that in your README.md ;-)

And indeed am using the trick rupertbg mentioned for GMail to basically use the same e-mail three times just wth different + tags in it.

Previous post:
Hi, have a similar but different issue. Have now setup three different accounts for my three different Panasonic units in my home. The three different accounts work in the Panasonic app.
However, in homebridge, only the first one works while the other two do not, it gives a 'Error - 403 Forbidden. Check the configured email and password, then restart Homebridge. null' error'. Which is very strange, as I double and triple checked the credentials.

What could be the issue here? Will for obvious reasons not post my credentials here, but might it be that special characters in my passwords need escaping for example? Use fully randomised complex unique passwords with special charactes included.

For reference, my JSON setup, anomynised without credentials:

    "accessories": [
        {
            "accessory": "PanasonicAirConditioner",
            "name": "Airco 1",
            "email": "<<<e-mail 1>>>",
            "password": "<<<password 1>>>",
            "devicenumber": 1
        },
        {
            "accessory": "PanasonicAirConditioner",
            "name": "Airco 2",
            "email": "<<<e-mail 2>>>",
            "password": "<<<password 2>>>",
            "devicenumber": 2
        },
        {
            "accessory": "PanasonicAirConditioner",
            "name": "Airco 3",
            "email": "<<<e-mail 3>>>",
            "password": "<<<password 3>>>",
            "devicenumber": 3
        }
    ],

**Comment by JurgenLB** [comment]
It is solved but for future reference ;
Yes the Devicenumber is only necessary if you have multiple devices on your Panasonic account.
If you use a defferend e-mail for every device you have multiple Panasonic accounts with only 1 device.
So in that situation there is no need for  Devicenumber in your config file

**Comment by codyc1515** [comment]
This plug-in is now archived and it is advised to use the [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform) plug-in instead. It is based on this plug-in. This plug-in provides support for the devices as a platform (instead of just individual accessories).
