### ISSUE TITLE
Support for multiple units

### ISSUE THREAD

**Issue by arkadicolson** [codyc1515/homebridge-panasonic-air-conditioner#34]
Is there a chance that multiple units will be supported in the future?

**Comment by codyc1515** [comment]
You can already can using the config UI. It's under advanced configuration. Ideally someone would be able to support me to transform this plugin from an accessory to a platform so that multiple can be supported by default. Until then this works.

**Comment by arkadicolson** [comment]
Ok but that's to select for example the second one but not to show them 
all? If I enter 2 in the advanced config the second unit will be used?
