### ISSUE TITLE
Updating on Hoobs

### ISSUE THREAD

**Issue by connor165** [codyc1515/homebridge-panasonic-air-conditioner#36]
Hey codyc1515,

I have noticed that there have been a few updates to the files for the Homebridge plugin, however there doesn't seem to be any prompt to update on Hoobs, as I am still getting the new app version error: `Login failed. Error # 4106 New version app has been published`. I'm currently on homebridge-panasonic-air-conditioner v3.3.4. I've tried manually installing the latest version but it still resorts to v3.3.4. Would appreciate if there was any way in which this could be resolved.

Cheers,
connor165

**Comment by arkadicolson** [comment]
I have the same problem...

**Comment by ursusHU** [comment]
The shitty Panasonic app was changed again. And it seems the current login procedure is not working anymore.

**Comment by codyc1515** [comment]
Sorry about this. Yes, the Panasonic app is trash. Shame that there is almost next to no AC’s with HomeKit integrated. I have updated this plugin now.

**Comment by rupertbg** [comment]
If anyone finds this in the future and needs to rig up a fix in the meantime just jump into you node_modules folder in your homebridge data folder (e.g. vi `/opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js`) and edit line 30 to match the new version (I found the latest version number in the iOS App Store release notes for the Comfort Cloud app)

https://github.com/codyc1515/homebridge-panasonic-air-conditioner/blob/master/index.js#L30

**Comment by codyc1515** [comment]
The Panasonic validation is not good. It just needs to be the current version, or higher. Theoretically you could put version 30.0.0 and it will work forever. This is not recommended as the API may change causing unexpected behaviour.

**Comment by macaulai** [comment]
E325: ATTENTION
Found a swap file by the name "/var/tmp/index.js.swp"
          owned by: pi   dated: Fri Jan 22 20:15:22 2021
         file name: /opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js
          modified: YES
         user name: pi   host name: homebridge
        process ID: 2102
While opening file "/opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js"
      CANNOT BE FOUND
(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/var/tmp/index.js.swp"
    to avoid this message.

"/opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js" [New DIRECTORY]
Press ENTER or type command to continue
