### ISSUE TITLE
Suddenly my ACs not recognized 

### ISSUE THREAD

**Issue by ursusHU** [codyc1515/homebridge-panasonic-air-conditioner#41]
I get the following messages (see screenshot), if I restart Homebridge. I also realized that the connection with the Panasonic comfort cloud app also not smooth.
![318A4623-F880-4815-9D66-2584B285B2DA](https://user-images.githubusercontent.com/61931127/97357156-a0192f00-1899-11eb-9c14-1728896728a8.jpeg)

**Comment by arkadicolson** [comment]
Panasonic comfort cloud had some trouble I think. I had the same issue. 
It's ok now again.
