### ISSUE TITLE
Question: what’s the purpose of the on/off button?

### ISSUE THREAD

**Issue by ursusHU** [codyc1515/homebridge-panasonic-air-conditioner#47]
Hi,
Thank you very much for the fix! :)
I have two questions regarding the new layout.
There is an extra power button below the normal wheel. What is the purpose of this? I mean I can turn on the unit with the wheel, but with this button it seems I can’t control the unit.
![789F6545-E115-4052-9661-54F29DA9677F](https://user-images.githubusercontent.com/61931127/103455266-f9fc0200-4ceb-11eb-99f4-a0af937e9d2a.png)
The second question is about the 2 buttons at the lower end. They are not really readable and using the naming of the unit. What are the purpose of those buttons?
![1FC336D7-A344-44BF-9970-1FC69AF4EA1F](https://user-images.githubusercontent.com/61931127/103455293-36c7f900-4cec-11eb-980a-7982188ed739.png)
Thank you very much!

**Comment by codyc1515** [comment]
Hi there. Good question! I had the same issue. I believe both are HomeKit app bugs. The button is related to the Dehumidifier / Dry function, the buttons underneath the slider (Fan) are for Fan Mode (auto / manual) and Oscillate (swing mode).

![image](https://user-images.githubusercontent.com/50791984/103456217-ecc92c80-4d58-11eb-84b5-e937bf2f50ce.png)![image](https://user-images.githubusercontent.com/50791984/103456221-efc41d00-4d58-11eb-8c9d-981572653d00.png)![image](https://user-images.githubusercontent.com/50791984/103456223-f18de080-4d58-11eb-9bf7-c577b6fc8834.png)

**Comment by codyc1515** [comment]
Oh using it as three separate tiles causes everything to look proper but is a bit messy.

**Comment by arkadicolson** [comment]
Is there a way to use it again as 1 tile or is it caused also by this bug?

**Comment by JurgenLB** [comment]
this is a setting in your Home-app to use the accessoiry as seperate tile or as 1 tile
I have mine as 1 tile
![Schermafbeelding 2021-01-17 om 20 49 06](https://user-images.githubusercontent.com/77586573/104854183-9e459180-5905-11eb-95a8-fe32e7fc2d24.png)

**Comment by arkadicolson** [comment]
Currently they are exposed as separate tiles and the button is saying "Toon als aparte tegels"... And when I power on the airco, there appears a third tile, the fan...

**Comment by codyc1515** [comment]
You can choose - as above - to have the as one tile. I think the question was answered above.
