### ISSUE TITLE
Version 5.0 removes fan speed adjustment for air-conditioner

### ISSUE THREAD

**Issue by putthegundownkinkade** [codyc1515/homebridge-panasonic-air-conditioner#48]
If i adjust the fan speed it switches the air conditioner off. 

So i can set air temperature but not the speed of the fan using the air-con tile

**Comment by rupertbg** [comment]
Hey @putthegundownkinkade can you post your Panasonic model number?

**Comment by putthegundownkinkade** [comment]
Hey @rupertbg 

 I have a 2.5kw and a 5kw TKR and a 7.1kw VKR

All have CZ TACG1 wifi adapters

**Comment by codyc1515** [comment]
There's a few reasons for this. HomeKit doesn't support a Thermostat with a Fan, only a HeaterCooler. However this doesn't work correctly with the Heat Pumps as they only have one threshold temperature (not two). Instead I implemented the Fan function of the Heat Pump which is the behaviour you're seeing. I'll have to think about this a bit more how we can solve it.

**Comment by putthegundownkinkade** [comment]
The prior functionality worked well for me. 

You could tap the icon in HomeKit to toggle the air conditioner on/off and long press to adjust temperature and mode etc. 

Is it no longer possible to show it like that?

edit: also fan speed is now a separate function so if I adjust fan speed it turns of the air conditioner and just works as a fan. I can set temperature for the aircon but not fan speed

**Comment by codyc1515** [comment]
How is it now?

**Comment by putthegundownkinkade** [comment]
It’s fantastic now!

**Comment by codyc1515** [comment]
Glad to hear! :)
