### ISSUE TITLE
Login failed due to new app versioned released

### ISSUE THREAD

**Issue by BaskaraR** [codyc1515/homebridge-panasonic-air-conditioner#52]
Unable to access home kit as the device is not responding;
Following the error shown:

[1/21/2021, 3:12:15 PM] [Master Bedroom AC] Login failed. Error # 4106 New version app has been published

**Comment by macaulai** [comment]
E325: ATTENTION
Found a swap file by the name "/var/tmp/index.js.swp"
          owned by: pi   dated: Fri Jan 22 20:15:22 2021
         file name: /opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js
          modified: YES
         user name: pi   host name: homebridge
        process ID: 2102
While opening file "/opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js"
      CANNOT BE FOUND
(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r /opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "/var/tmp/index.js.swp"
    to avoid this message.

"/opt/homebridge/node_modules/homebridge-panasonic-air-conditioner/index.js" [New DIRECTORY]
Press ENTER or type command to continue

**Comment by codyc1515** [comment]
Pushed the fix now. It's due to the Panasonic app change.
