### ISSUE TITLE
Warning on beta version homebridge

### ISSUE THREAD

**Issue by arkadicolson** [codyc1515/homebridge-panasonic-air-conditioner#54]
I'm getting this warning when running Homebridge on 1.3.0-beta53:

Received warning for the plugin 'homebridge-panasonic-air-conditioner' from the characteristic 'Target Heating Cooling State': SET handler returned write response value, though the characteristic doesn't support write response!

**Comment by codyc1515** [comment]
Are you still seeing this issue?

**Comment by arkadicolson** [comment]
I'm running v1.3.4 and seeing these warnings:

[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Rotation Speed': 
characteristic was supplied illegal value: number 0 exceeded minimum of 
1. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Cooling Threshold 
Temperature': characteristic was supplied illegal value: number 10 
exceeded minimum of 16. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Heating Threshold 
Temperature': characteristic was supplied illegal value: number 0 
exceeded minimum of 16. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Rotation Speed': 
characteristic was supplied illegal value: number 0 exceeded minimum of 
1. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Cooling Threshold 
Temperature': characteristic was supplied illegal value: number 10 
exceeded minimum of 16. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Heating Threshold 
Temperature': characteristic was supplied illegal value: number 0 
exceeded minimum of 16. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Rotation Speed': 
characteristic was supplied illegal value: number 0 exceeded minimum of 
1. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Cooling Threshold 
Temperature': characteristic was supplied illegal value: number 10 
exceeded minimum of 16. See https://git.io/JtMGR for more info.
[3/22/2021, 8:38:08 AM] [homebridge-panasonic-air-conditioner] This 
plugin generated a warning from the characteristic 'Heating Threshold 
Temperature': characteristic was supplied illegal value: number 0 
exceeded minimum of 16. See https://git.io/JtMGR for more info.
[3/22/2021, 5:23:22 PM] [Keuken] Refresh failed. Device may be offline or in error state. Online true Error Status Flag false HTTP 200 Error # undefined undefined
Arkadi

**Comment by arkadicolson** [comment]
I'm seeing these messages now:

This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

Not urgent but annoying because my logs are filling up with these messages :-)

**Comment by codyc1515** [comment]
Fixed.

**Comment by JurgenLB** [comment]
I just updated homebridge and plugin an now i have;
I think this is releated or is this a "new issue"
This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://git.io/JtMGR for more info.

This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 16. See https://git.io/JtMGR for more info.

**Comment by codyc1515** [comment]
I have searched other plugins and they have found that there is no way to fix the threshold issue. This is because of the way Homebridge works out the defaults.

**Comment by JurgenLB** [comment]
OK and thank you for the hard work
