### ISSUE TITLE
Token error. Refresh failed

### ISSUE THREAD

**Issue by BaskaraR** [codyc1515/homebridge-panasonic-air-conditioner#57]
hi there,

I've been getting this error msg suddenly since awhile ago " refreshed failed. Token error. The token may have expired. null". Homekit shows the ac is on however physically the ac is not turned on. Refreshing homebridge fixes the error, then awhile later when the Ac is turned off and on again error returns again.

Running Homebridge with Raspberry Pi

thanks

**Comment by rupertbg** [comment]
@codyc1515 this is fixed in https://github.com/codyc1515/homebridge-panasonic-air-conditioner/pull/50

**Comment by codyc1515** [comment]
Thanks Rupert. Should be sorted now.
