### ISSUE TITLE
Refresh failed error message in log, however the unit seems to work

### ISSUE THREAD

**Issue by ursusHU** [codyc1515/homebridge-panasonic-air-conditioner#59]
I have the following error message, but fortunately this is not affecting the control of the AC.
![D0956447-F2BA-40F6-BC78-B8DEF02DD2D7](https://user-images.githubusercontent.com/61931127/111897522-9e0a6500-8a20-11eb-819c-b6780644a262.jpeg)

**Comment by ursusHU** [comment]
I have updated also Homebridge now, some new error messages appearing 
![23B42D8C-5623-4E1F-815E-76A47162D9DB](https://user-images.githubusercontent.com/61931127/111904196-e1c39580-8a45-11eb-8006-3c34709635aa.jpeg)

**Comment by codyc1515** [comment]
There should be less messages now but some of these appear to Homebridge bugs which I will have to lodge.

**Comment by codyc1515** [comment]
This should be sorted now in 6.1.2.
