### ISSUE TITLE
Question: after updates unit reappears

### ISSUE THREAD

**Issue by ursusHU** [codyc1515/homebridge-panasonic-air-conditioner#60]
After the updates usually the unit reappears in HomeKit which results that all of the existing automations have to be reviewed and fixed. Couldn’t this be avoided? Thanks!

**Comment by codyc1515** [comment]
Apologies but this was necessary when we switched from Heater Cooler to Thermostat and then back to Heater Cooler.

**Comment by ursusHU** [comment]
No problem, thanks for clarifying.
