### ISSUE TITLE
Refresh failed. Device may be offline or in error state

### ISSUE THREAD

**Issue by miguelsasso** [codyc1515/homebridge-panasonic-air-conditioner#63]
Plugin has been working well for months without issue.  Has started throwing errors in the past 24 hours.  I did try updating HOOBS and  plugin to latest versions.

I can still turn the air con unit on, but when I go back into the Home app a minute later, it gives the wrong status (status is off when unit is turned on).

13/04/2021, 08:14:09 [Air Con 1] Refresh start
13/04/2021, 08:14:10 [HOOBS DABD@Air Con 1@Air Con 1@Target Heater-Cooler State] characteristic value expected valid finite number and received "undefined" (undefined)
13/04/2021, 08:14:10 [Air Con 1] Refresh failed. Device may be offline or in error state. OnlineStatus false ErrorStatus false HTTPStatus 200 Error # undefined undefined

**Comment by BaskaraR** [comment]
I'm facing same issue as well!!! 
[13/04/2021, 13:30:57] [Master Bedroom AC] Refresh failed. Device may be offline or in error state. OnlineStatus false ErrorStatus false HTTPStatus 200 Error # undefined undefined

The plugin is updated to the latest version. Also some of my units is actually turned off but in homebridge it  appears to be "ON" when its actually "OFF"

**Comment by miguelsasso** [comment]
Possibly same issue as #61

**Comment by codyc1515** [comment]
The Panasonic server was having issues overnight. I’ve updated the error handling to better describe the issue when this happens, alongside a recommendation to resolve the issue. Hope to post it tonight (following my testing).

**Comment by miguelsasso** [comment]
Hi @codyc1515 

Appreciate your work to maintain this plugin.  

The same error appears to be eventually killing homebridge:

15/04/2021, 09:02:06 [HOOBS DABD@Air Con 2@Air Con 2@Target Heater-Cooler State] characteristic value expected valid finite number and received "undefined" (undefined)
15/04/2021, 09:02:08 [HOOBS DABD@Air Con 1@Air Con 1@Target Heater-Cooler State] characteristic value expected valid finite number and received "undefined" (undefined)
15/04/2021, 09:03:25 Got SIGTERM, shutting down Bridge...

I don't know how long the service was active for before it crashed, probably about 24 hours.

Thanks

**Comment by moranchoj** [comment]
Same problem with Hoobs 3.3.5 and pluging version 6.6.1

HOOBS 9DB6@Fresquet Menjador@Fresquet Menjador@Target Heater-Cooler State] characteristic value expected valid finite number and received "undefined" (undefined)
16/4/2021, 17:33:40 [Fresquet Menjador] Refresh failed. Device may be offline or in error state. OnlineStatus undefined ErrorStatus undefined HTTPStatus 200 Error # undefined undefined

**Comment by codyc1515** [comment]
Just pushed the update (6.1.2) now which improves the exception handling when the Panasonic server is having issues. Let me know if this helps. It should remove the 200 error (false positive).

The Homebridge instance should not be crashing. Prior to this update I had nearly a month uptime on the Homebridge instance. Since the update I have had 100% uptime also. If you are experiencing crashes, you need to upload your entire log (not just the parts that you think are relevant) to enable me to review and identify the root cause.

The Characteristic errors will continue until I can work out how exactly to resolve these (the documentation isn’t that clear). These generally don’t cause any issue and are more of a warning. They can potentially cause issues with Siri and “No response”, however I have never encountered these to date.

**Comment by miguelsasso** [comment]
Ok I will update and test. 

Until this particular issue started, I have also found the plug-in to be extremely stable. 

Thanks again

**Comment by codyc1515** [comment]
Yeah sorry. I released 6.1.2 cause it looks like Panasonic removed the online flag (which we were detecting):

**Comment by moranchoj** [comment]
Hi,

I have been running the 6.1.2 version for 12 hours and no crashes at all. I have not done any change in the pluging or Hoobs configuration.

Most of the error messages have dissapeared but still a couple of warnings are shown. In any case, the heaters-coolers (i have 2 devices attached to the same compressor) seems to work well

18/4/2021, 11:04:26 [HOOBS 9DB6@Fresquet Papes@Fresquet Papes@Target Heater-Cooler State] characteristic value expected valid finite number and received "undefined" (undefined)
18/4/2021, 11:04:27 [Fresquet Papes] Warning - Device has lost connectivity to Comfort Cloud. Check your Wi-Fi connectivity or restart the Heat Pump. undefined undefined

Lost connectivity message has to be a wrong message as devices works well and answer fast from Panasonic app but also from Homekit app.

I am most worried about the "expected valid finite number and received "undefined" (undefined)” message.

Thanks codyc1515!!!

**Comment by moranchoj** [comment]
I have updated to the 6.1.4 version just now. Only after few minutes working I see that the "lost connectivity" warning message has dissapeared but not the rest.

Still 2 warning/error messages appear:

1) 401 Unauthorized. Login token has expired. null
2) expected valid finite number and received "undefined" (undefined)

To understand the log file, I have 2 heaters-cooler, "Fresquet Papes" and "Fresquet Menjador", attached to the same compressor unit.

18/4/2021, 11:27:23 [Fresquet Papes] Refreshed succesfully
18/4/2021, 11:28:17 [Fresquet Menjador] Refresh start
18/4/2021, 11:28:18 [Fresquet Menjador] Warning - 401 Unauthorized. Login token has expired. null
18/4/2021, 11:28:22 [Fresquet Papes] Refresh start
18/4/2021, 11:28:23 [Fresquet Papes] {
  dryTempMin: -1,
  modeAvlList: { autoMode: 1, fanMode: 1 },
  airSwingLR: true,
  nanoe: false,
  autoMode: true,
  autoSwingUD: false,
  ecoNavi: false,
  heatTempMax: -1,
  temperatureUnit: 0,
  iAutoX: false,
  coolTempMin: -1,
  autoTempMin: -1,
  quietMode: true,
  powerfulMode: true,
  timestamp: 1618737848000,
  fanMode: false,
  coolMode: true,
  summerHouse: 0,
  coolTempMax: -1,
  permission: 2,
  dryMode: true,
  heatMode: true,
  fanSpeedMode: -1,
  dryTempMax: -1,
  autoTempMax: -1,
  fanDirectionMode: -1,
  ecoFunction: 0,
  heatTempMin: -1,
  parameters: {
    ecoFunctionData: 0,
    airSwingLR: 2,
    nanoe: 1,
    ecoNavi: 0,
    ecoMode: 0,
    operationMode: 0,
    fanAutoMode: 0,
    temperatureSet: 20,
    fanSpeed: 0,
    iAuto: 0,
    airQuality: 0,
    insideTemperature: 19,
    outTemperature: 16,
    operate: 0,
    airDirection: 0,
    actualNanoe: 1,
    airSwingUD: 2
  }
}
18/4/2021, 11:28:23 [HOOBS 9DB6@Fresquet Papes@Fresquet Papes@Target Heater-Cooler State] characteristic value expected valid finite number and received "undefined" (undefined)
18/4/2021, 11:28:23 [Fresquet Papes] Refreshed succesfully

**Comment by codyc1515** [comment]
The token expiring is quite normal. There can be a couple of reasons for this.

Namely if you didn’t create a separate login for the Homebridge instance vs. the app on your phone then you will experience logging out behaviour. This will also happen if you have two instances of the plug-in running as I have not yet figured out how to add the platform support, so each must be added individually (= 2 logins = they will be perpetually logging each other out). In the meantime, create a separate login for each heat pump.

The other is simply the token expiring. Seeing a good refresh, like you posted, more or less immediately after the token expiring is a good sign and shows that the service recovered itself by logging in again once more.
