### ISSUE TITLE
After reboot Homebridge (or Pi) no response in Homekit

### ISSUE THREAD

**Issue by duckdany** [codyc1515/homebridge-panasonic-air-conditioner#66]
Hello,

After I added the device in HomeKit (with separate bridge) I could control my air conditioner over internet too in HomeKit. If the bridge, Homebridge or Pi reboot there is no response in HomeKit from my bridge and device too. So I couldn't control it. I tried too reboot it (bridge and home bridge too) so many times but no response. I have to add the device and bridge again to HomeKit.
I made a separate user for my air conditioner like in the manual here.
My Air conditioner is a TZ25, which has a built-in wifi controller.
My hub is an iPad Air (1st generation).

Thank you!

**Comment by JurgenLB** [comment]
In the beginning I have also used a iPad for hub, but that was not a thrustful situation
now I have a HomePod (First gen) and everything is more stable.
Do you have homebridge running as a service?

**Comment by codyc1515** [comment]
This needs more information. Are any other devices in Homebridge working?

**Comment by duckdany** [comment]
Hello,
I had the same situation as JurgnLB. First my hub was a 1st gén iPad Air with iOS 12.5. And the problem was that I mentioned.
Now I have a HomePod mini and the air conditioner is always reachable.
I kept the iPad as a second, backup hub. The iPad couldn't see the air conditioner but it's not a problem anymore.
Thank you!

**Comment by codyc1515** [comment]
Ah okay. It may be an issue with non recent iOS.
