### ISSUE TITLE
Plugin's new versions not on this repository

### ISSUE THREAD

**Issue by efipso** [codyc1515/homebridge-panasonic-air-conditioner#69]
Hi,

I can see in this repository that actual version of that plugin es 6.1.1. But homebridge/npm updated it with versions 6.1.2, 6.1.3, 6.1.4 and 6.1.5.
Under my point of view it's strange that an update was published but the repository remains without changes. Maybe I'm losing something, but... Are those updates legal? Or somehow, someone else are publishing updates of your plugin on NPM without your permission?

Thank you,

**Comment by codyc1515** [comment]
Sorry I didn’t have a chance to post the update to GitHub yet. So yes it is out of sync. The update is not illegitimate. It fixes a check that Panasonics was doing on their servers.

**Comment by efipso** [comment]
I'm just worried if are not from you, but if the updates are legit it's all good! Thank you!!
