### ISSUE TITLE
4106 new version has been published

### ISSUE THREAD

**Issue by ManBearPig** [codyc1515/homebridge-panasonic-air-conditioner#70]
Hi,

I have Homebridge setup on a Raspberry Pi and it's been working without issues up until today, when the plug-in started giving me the following error:
"4106 New version app has been published"
It's kinda strange as I didn't get any update on my Apple devices in recent days so not sure where the issue is - was there indeed a new version published but not yet pushed to the Polish App Store, or is there something wrong with my setup?

Appreciate any help, can send whatever logs necessary.
Thanks

**Comment by ChrisFurlong** [comment]
+1

**Comment by BaskaraR** [comment]
I’m facing the same issue as well.

**Comment by bms2012** [comment]
+1

**Comment by ManBearPig** [comment]
Has anyone tried the method of changing the version name in one of the files of the plug-in to fool it into thinking that it's all up to date?
I have yet to get time to go around this, but not sure if this solves the problem this time around or if there's some bigger fix required.

Thx!

**Comment by bms2012** [comment]
Changing the version number still works:
look for the index.js in the node_modules dir (for my raspi: /usr/local/lib/node_modules/homebridge-panasonic-air-conditioner)
row 30: version is now "1.12.0"
restart homebridge

**Comment by xyz667** [comment]
> Changing the version number still works:
> look for the index.js in the node_modules dir (for my raspi: /usr/local/lib/node_modules/homebridge-panasonic-air-conditioner)
> row 30: version is now "1.12.0"
> restart homebridge

Could you please clarify - just changing the version number in the local js and it is possible to connect to the Pana Comfort Cloud again?

**Comment by bms2012** [comment]
Yes, there are still other errors left, but it works again with homekit

**Comment by BaskaraR** [comment]
Hi all, 
Any idea on how to make this changes in local js. How do I access this directory? I’m kinda new to this. I’m running HomeBridge with raspberry pi. Thanks

**Comment by ManBearPig** [comment]
bms2012 thanks for confirmation, it does work!.

So for anyone else who has no clue what they're supposed to do:
1. [HERE](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Connect-Via-SSH) is a guide on how to make an SSH connection to RPi - I'm on Win10 so just used basic CMD
2. Once you're there, [HERE](https://www.smarthomebeginner.com/most-used-ssh-commands-raspberry-pi/) are the most frequently  (supposedly) used commands. As I had no clue whatsoever I just typed 'sudo nano /usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js' and it opened the file mentioned above by bms2012.
3. edit the line as they mentioned, hit CTRL+O, then Enter, restart homebridge and it _should_ work

Had to do some digging, and as this is the first time I touched CMD in my life, perhaps this kind of a dummy guide might be useful for someone with my ... experience.
Cheers

**Comment by BaskaraR** [comment]
Hi All,

Thanks for your inputs. Yes, it does work now!!! Cheers

**Comment by saushun** [comment]
i am using Container station on QNAP NAS and got the same problem, how should i fix it?

**Comment by putthegundownkinkade** [comment]
I am now having this issue however my version is already "1.12.0"

is there a ne app on the App Store as I haven't received it here in Australia. if there is does anyone have the version number.

EDIT, it's 1.13.

I used 

sudo nano /usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js

**Comment by CharlesMonneron** [comment]
> I am now having this issue however my version is already "1.12.0"
> 
> is there a ne app on the App Store as I haven't received it here in Australia. if there is does anyone have the version number.
> 
> EDIT, it's 1.13.
> 
> I used
> 
> sudo nano /usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js

worked for me thank you @putthegundownkinkade .

**Comment by bpotter79** [comment]
incase anyone else is running Hoobs V4 the directory structure / command is
sudo nano /var/lib/hoobs/hoobs/node_modules/homebridge-panasonic-air-conditioner/index.js

**Comment by guwo65** [comment]
I had the Same Problem today and a Bit more, so i made the Changes written By putthegundownkinkade in #70 and by CharlesMonneron in #65.
And it  Works . No more Warnung and errors.
Thx to both!!!
My homebridge is Running in docker on QNAP.

**Comment by codyc1515** [comment]
Sorry about this. I have made it easier to update in the future.

**Comment by CharlesMonneron** [comment]
> I am now having this issue however my version is already "1.12.0"
> 
> is there a ne app on the App Store as I haven't received it here in Australia. if there is does anyone have the version number.
> 
> EDIT, it's 1.13.
> 
> I used
> 
> sudo nano /usr/local/lib/node_modules/homebridge-panasonic-air-conditioner/index.js

It is 1.14 now
