### ISSUE TITLE
Failed to login error

### ISSUE THREAD

**Issue by saushun** [codyc1515/homebridge-panasonic-air-conditioner#71]
It happens again, thought panasonic is changing the login authentication method periodically.

**Comment by walternijenhuis** [comment]
Same here! Login failure since last night.

**Comment by 1homebridge** [comment]
I’m also unable to login since yesterday. Getting warning about plug-in exceeding value 0 and 10. Can anyone advise how to repair this?

**Comment by Dave7NL** [comment]
Same here 
Failed to login. Check the configured email and password, then restart Homebridge. 4106 New version app has been published

**Comment by 1homebridge** [comment]
> Same here
> Failed to login. Check the configured email and password, then restart Homebridge. 4106 New version app has been published

Are you also getting a cooling/heating threshold temperature error in your log?
Thanks

**Comment by jinie** [comment]
Same here

`[09/09/2021, 21.48.46] [heatpump] Failed to login. Check the configured email and password, then restart Homebridge. 4106 New version app has been published
`
`[09/09/2021, 21.48.46] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://git.io/JtMGR for more info.`

`[09/09/2021, 21.48.46] [homebridge-panasonic-air-conditioner] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 16. See https://git.io/JtMGR for more info.`

**Comment by magnusaurus** [comment]
Same issue here

**Comment by jinie** [comment]
The "quick and dirty" solution is to find the relevant file on your Homebridge server, on mine it's in `/usr/lib/node_modules/homebridge-panasonic-air-conditioner` and edit the `index.js` file to update the app version in the top of the file to `const APP_VERSION = "1.13.0";`

I would submit a pull request with the change, but the version on Github is NOT the same version that is released on NPM.

**Comment by codyc1515** [comment]
This is not a bug really. The version changed. It is now easier to update however at the top of the index.js file.
