### ISSUE TITLE
Failed to login. Check the configured email and password, then restart Homebridge. 5300

### ISSUE THREAD

**Issue by BaskaraR** [codyc1515/homebridge-panasonic-air-conditioner#74]
Hi there,  

It’s been all fine, until today I’m unable to turn/ off the ac. 
I’m  using homebridge  v 1.3.6 with Pi

Node.js Version | v14.18.1
Node npm v6.14.15

**Comment by codyc1515** [comment]
Did you check the app? The server is down.
