### ISSUE TITLE
Code sync with npm

### ISSUE THREAD

**Issue by embee8** [codyc1515/homebridge-panasonic-air-conditioner#75]
Hello! I'm considering contributing to this project but the latest release on npm is not in sync with Github, which essentially makes creating pull requests pointless.

@codyc1515, what's your current release and maintenance setup? Anything that the community can help with?

**Comment by HomekitDave** [comment]
Forgive me for jumping in @codyc1515! @embee8, off the top of my head I know two things which are often brought up…

- Convert the plug into a platform, so it supports multiple accessories. 
- An issue which breaks the connection when Panasonic updates the API version, “New version app has been published” (e.g. #52)

**Comment by embee8** [comment]
Thanks for the summary, that is helpful. I'm hoping we can establish a release process so that we collaborate here on GitHub and then push the changes to npm, rather than this repository just mirroring npm (currently also out of sync it seems).

**Comment by codyc1515** [comment]
Hi. I will sort tonight. Appreciate the offer of help. I struggle with adapting the plugins to the platform concept.

**Comment by embee8** [comment]
Any luck with updating the repo to the latest version? I'm happy to send a PR your way if you like.

**Comment by codyc1515** [comment]
Sorry for the delay. I have sorted now.
