### ISSUE TITLE
Road to Platform Plugin

### ISSUE THREAD

**Issue by embee8** [codyc1515/homebridge-panasonic-air-conditioner#77]
Hi all!

I explored how to transform this project into a platform-style plugin and have a working prototype ready. I will conduct some more testing before publishing it but wanted to check in with the creator/maintainer of this project and the community to discuss how to go about it.

Characteristics of the fork:
- Support for multiple devices (only one account required)
- Dynamic setup of accessories based on what's configured on Comfort Cloud
- App version can be configured in the settings (to remove the dependency on the project to push a fix)
- Uses the latest platform plugin specs as per Homebridge developer docs

Merging the base project with the fork might make for a very bumpy upgrade path because I changed quite a few things (in line with the current plugin developer docs), including a different structure of the settings and accessories.

I might actually have changed so much that an existing installation would break after the upgrade, or at least result in an unclean config mixing old and new settings.

There might be people out there who are happy with one device only, and I am wary of updating a well-working plugin with a version that might have a beta character to begin with.

Since Homebridge doesn't seem to have a beta versioning framework afaik, my personal preference is to publish the project as new package, let people test it without wrecking their functioning setups, and then we can reconvene and discuss where we go from there to keep this project thriving.

Would love to hear your opinion.

**Comment by arkadicolson** [comment]
Hi

Great news! I have 3 units and am looking forward to test it. Just let me know in which way you will provide the new code after having it discussed with the creator/maintainer.

Br
Arkadi

**Comment by codyc1515** [comment]
Sounds great! Where can I see it?

**Comment by codyc1515** [comment]
Bump

**Comment by embee8** [comment]
I've been running it on my local installation for a bit longer and optimised a few bits.

Repository: https://github.com/embee8/homebridge-panasonic-ac-platform
Package: https://www.npmjs.com/package/homebridge-panasonic-ac-platform

**Comment by codyc1515** [comment]
Looks great! Thank you for your work.

Only a few suggestions:

1. Model value does not populate in Home app (just shows as `Default-Model`) - I think this relates to the accessory.context.device.deviceModuleNumber value
2. X-APP-VERSION is populated from this.config.appVersion and this is populated as a placeholder (hidden) in config-ui-x, however the default behaviour of config-ui-x is that even placeholder values get hardcoded. I would suggest to avoid this to treat it the same as User-Agent / COMFORT_CLOUD_USER_AGENT by including it in the settings.ts file.
3. Regarding dehumidifier and fan. We _can_ technically add both of these but I quickly became confused trying to make each of the functionality operate independently. For example turning on dehumidification service will turn off the heater cooler service. This is just the way HomeKit behaves.
4. Regarding threshold temperature. Thermostats allow one temperature to be set for both heating and cooling thresholds. This matches more closely with Panasonic Air Conditioners behaviour, however the thermostat service has limitations (namely you cannot have a rotation speed). Again, this is just the way HomeKit behaves.

What do you feel is the way forward? Do I depreciate this one or migrate your files over?

**Comment by embee8** [comment]
It might be worth keeping this repo alive, depending on the specific needs of the existing user base (since there are a variety of systems out there). I've only entered the Homebridge scene, so I'll leave that call to you.

As for the feedback - thank you!

1. It populates correctly on my installation. If the issue persists, feel free to create an [issue in the repo](https://github.com/embee8/homebridge-panasonic-ac-platform/issues).
2. This is intentional to allow non-code adaptions to bump the app version. Downside is that people might run different setups while being on the same plugin version, but possibly better than a non-functional plugin while waiting for maintainers to fix it. *Edit: Thought about this a bit more and the trade-off is less attractive if we assume that the plugin is kept up-to-date. Might switch strategies going forward.*
3. Will revisit this at a later point.
4. Same as 3.
