### ISSUE TITLE
Could not login to Panasonic account

### ISSUE THREAD

**Issue by efipso** [codyc1515/homebridge-panasonic-air-conditioner#9]
Since yesterday, I lost conection with de AC. When I debug the homebridge instance I can see the following messages:
[Panasonic AC] Initializing PanasonicAirConditioner accesory...
[PanasonicAC] Could not login to Panasonic account

Of course, I tried to use that login into the app and works fine, so is not an account issue

**Comment by efipso** [comment]
Just seen the Pull Request made by @antgeo and apply mannually the changes and I can confirm that works great

**Comment by codyc1515** [comment]
Fixed in #8 

The Panasonic API I have used is from the mobile app and requires us to send the version numbest each time. While annoying it kind of makes sense that they only want people using the latest version. Unfortunately it means for us that we need to update the plug-in each time.

**Comment by efipso** [comment]
Great, now we know it in the future!

**Comment by codyc1515** [comment]
I have just pushed the fix.
